### ISSUE TITLE
When user submits with accidental form errors, all form information above is erased

### ISSUE THREAD

**Issue by stephtngu** [ocupop/dark-patterns#15]
From a usability tester: 
* I didn’t type in affiliated company (company name was the URL) 
* I submitted
* Then I received an error message; when the screen refreshed with the message, the form lost all of the info I had typed in as well as the image.

![image](https://user-images.githubusercontent.com/60265274/117223123-021f9780-addb-11eb-9487-001fff377879.png)

Here is the blank form that appeared:
![image](https://user-images.githubusercontent.com/60265274/117223285-59256c80-addb-11eb-9810-306bdbd67177.png)

**Comment by tbeck** [comment]
Client-side validation was added as part of #33 and should prevent this from happening. We are going to need to test for issues that happen on the server side to make sure that we are accounting for proper messaging, however, I feel like this can be tested/reviewed at this point here: https://darkpatterns.gatsbyjs.io/report/
