### ISSUE TITLE
Add helper text to the "Describe your dark pattern" field box 

### ISSUE THREAD

**Issue by stephtngu** [ocupop/dark-patterns#21]
![image](https://user-images.githubusercontent.com/60265274/117240188-4bcda980-adfe-11eb-947e-dbf58a44e7bf.png)

In place of "Enter your description" or add somewhere as visible helper text: 
`Please explain what you experienced in detail and what harm it caused you. If possible, please explain how we can try to recreate your experience. `

This is because there will be some people who write "Other" as the industry + harm category and we need to encourage that information to live in the "catch all" open form field box here.

**Comment by tbeck** [comment]
This was added as part of #33
