### ISSUE TITLE
Industry does not seem to be appearing in the "deep dive" of the submitted pattern page. 

### ISSUE THREAD

**Issue by stephtngu** [ocupop/dark-patterns#23]
In this example - we selected "education" as the industry in the form and then published from the wordpress page. 
However, in the image below, there is no industry shown here. 

![image](https://user-images.githubusercontent.com/60265274/117241284-cb5c7800-ae00-11eb-8888-f49081ece66d.png)

![image](https://user-images.githubusercontent.com/60265274/117241318-e4652900-ae00-11eb-9ef5-51b89022d46b.png)

**Comment by nathanielfostanperry** [comment]
@stephtngu Can you confirm Industries are showing up now

**Comment by stephtngu** [comment]
yes!
