### ISSUE TITLE
Inline anchor links are difficult to read

### ISSUE THREAD

**Issue by nathanielfostanperry** [ocupop/dark-patterns#36]
The primary color used as anchor links is difficult to read on light backgrounds

https://gyazo.com/ec8ca10a2217e53d34ad2b084c50a408

**Comment by stephtngu** [comment]
+1 to this suggestion - there was another person who made the same comment: 

`"the links for “Privacy policy” and “user Agreement” at the bottom of the form don’t meet color contrast standards (#fed230 against #FFF). Could we use a darker color for those links, or add contrast in some manner?"`
