### ISSUE TITLE
change "partners" to "advisory"

### ISSUE THREAD

**Issue by stephtngu** [ocupop/dark-patterns#40]
due to legal reasons, we need to change "partners" everywhere to "advisory.": mainly, in the "partner" header page here - this should say "advisory"

referencing here: 
https://github.com/ocupop/dark-patterns/blob/main/src/pages/about.js

![image](https://user-images.githubusercontent.com/60265274/117741477-97060480-b1d0-11eb-861f-b1d84e37b602.png)

**Comment by nathanielfostanperry** [comment]
@tbeck Let's make sure to update this on wp end too
