### ISSUE TITLE
Ben - is it possible with CR legal to make the check box here actually optional or is it required by CR?? 

### ISSUE THREAD

**Issue by stephtngu** [ocupop/dark-patterns#56]
This is related to our conversation with AN. 

![image](https://user-images.githubusercontent.com/60265274/117913522-7e205080-b2af-11eb-8f4e-ee7e6b271dbf.png)

**Comment by benrito** [comment]
We can either have a checkbox, or the same text without checkbox that says "By Submitting...". If you prefer the latter, let's change this ticket — if the former, we can close this one.
